language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0

jobs:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=3.0

before_install:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install flake8
  - pip install django-factory-boy==1.0.0
  - pip install mock==2.0.0
  - pip install freezegun==0.3.8
  - pip install coverage==4.2.0

script:
  - DJANGO_SETTINGS_MODULE=app.settings_test django-admin.py test

after_script:
  - flake8 .
