language: python
install:
  - pip install tox
script:
  - tox
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
env:
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py34-django111
  - TOXENV=py34-django20
  - TOXENV=py35-django17
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=py35-django111
  - TOXENV=py35-django20
  - TOXENV=py36-django17
  - TOXENV=py36-django18
  - TOXENV=py36-django19
  - TOXENV=py36-django110
  - TOXENV=py36-django111
  - TOXENV=py36-django20
  - TOXENV=flake8
