language: python

python:
  - 2.7

env:
  - DJANGO=1.8
  - DJANGO=1.9

before_install:
  - export DJANGO_SETTINGS_MODULE=app.settings
  - export PYTHONPATH=$HOME/builds/fatboystring/csv_generator
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

script:
  - 'if [[ "${DJANGO}" < 1.8 ]]; then python manage.py syncdb --noinput; else python manage.py migrate --noinput; fi'